### ISSUE TITLE
Javascript error in chrome 44.0

### ISSUE THREAD

**Issue by bluety** [jasny/jquery.smartbanner#101]
Hello,

The script return an error in the console.
``Uncaught TypeError: $(...).addClass(...).one(...).emulateTransitionEnd is not a function (jquery.smartbanner.js:160)``

My configuration:
```javascript
jDocument.ready(function() {
    $.smartbanner({
        title: null,
        author: 'Darty',
        price: 'GRATUIT',
        appStoreLanguage: 'fr',
        inAppStore: 'Sur App Store',
        inGooglePlay: 'Sur Google Play',
        button: 'VOIR',
        iOSUniversalApp: false
    });
});
```

I don't understand emulateTransitionEnd function.

**Comment by jdalton** [comment]
The `emulateTransitionEnd` is a plugin added by jq.smartbanner.

**Comment by jdalton** [comment]
@bluety Can you provide a jsbin of the issue.

**Comment by jdalton** [comment]
Moving over to #102 .
