### ISSUE TITLE
Windows Store Link is wrong

### ISSUE THREAD

**Issue by xunderworldx** [jasny/jquery.smartbanner#124]
Instead of for windows 8.1: 
ms-windows-store:navigate?appid=

It should be:
ms-windows-store://pdp/?productid=

Also it doesn't using the Package Family Name, it uses the id shown at the very end of the windows 10 url shown in app identity in windows developer center. 

I noticed the Pack Family Name also doesn't work for the windows 8.1 version, you have to use the  id shown at the very end of the windows phone 8.1 url shown in app identity in windows developer center.

**Comment by jasny** [comment]
@xunderworldx Please send in a pull request, thanks.

**Comment by jdalton** [comment]
I added support for Windows 10 urls https://github.com/jasny/jquery.smartbanner/commit/dd9e3452010b3bbd9a26d3cf273446c6c941db3c.

Next step is to allow folks to specify an id for Win8 and Win10.
