### ISSUE TITLE
It's not working when open from weChat and Skype app

### ISSUE THREAD

**Issue by phanthinh** [jasny/jquery.smartbanner#137]
Hi everybody, 

I'm using iphone 5S and it's not working. I will shown step by step incorrect at below:

1. My App not install --> Open weChat or Skype --> Copy link and paste --> Click this link and work fine
1. App installed --> Open weChat or Skype --> Copy link and paste --> Click this link and not working now (It's still says "view app" although my app installed)

Best regards

**Comment by jdalton** [comment]
Hi @phanthinh!

I'm not sure what weChat or Skype have to do with it.
It sounds like something other than the jQuery plugin is the issue.

**Comment by phanthinh** [comment]
Oh, you shouldn't closed issue of me. But it's no problem at this time because me look good article for it (http://thescube.com/blog/app-banner-ios-android/) 

below are issue message:

> Currently the above meta tags does not work on iOS chrome browser. Jasny has produces a workaround that will show small banner on iOS chrome browser
> 
> http://jasny.github.io/jquery.smartbanner/
> 
> When we tested it, app banner worked great on chrome browser. How ever on safari there was two banners, one banner from the meta tag and another from the smart banner.

Ah, if you know how detection app installed in the mobile device, please share with me...

Best regards
