### ISSUE TITLE
Two banners show on Safari

### ISSUE THREAD

**Issue by ShovanSargunam** [jasny/jquery.smartbanner#90]
On Safari default app banner shows and your app banner shows below it. Is there a way to show only one banner?

**Comment by ShovanSargunam** [comment]
Eg http://s9.postimg.org/3sgqk09un/image.jpg

**Comment by jasny** [comment]
Please post the user agent string.

**Comment by jasny** [comment]
Note that on the demo site, it forces displaying the banner with the `force` option. Normally it won't display the jquery banner when the native smart banner is supported.

Please try it on you own site and close this issue if it works correctly for you.
