### ISSUE TITLE
Is there View and Open in Android?

### ISSUE THREAD

**Issue by Ricardo1980** [jasny/jquery.smartbanner#93]
Hello!

One question. If I have the installed in android, what is supposed I have to see in the banner? View (that opens the app store)? or Open (that opens the app directly)?

I ask this question because I have installed my app in my android but when I open the website, I see VIEW, if I press it, I see the app store, that says open because, well, my app is installed.

Thanks.

**Comment by shiratsu** [comment]
I have same problem on android.I don't want to show smart banner when i already have installed my app in my android.
is it possible?

**Comment by geerlingguy** [comment]
This is probably not possible due to (good) security limitations, meaning arbitrary javascript running in the browser can't read a list of installed apps on a device. But for individual apps, a workaround may be possible: http://stackoverflow.com/a/12901352

**Comment by jasny** [comment]
Thanks @geerlingguy for answering this question
